version: 2
project_name: mokey

before:
  hooks:
    - go mod tidy

builds:
  - id: mokey
    env:
      - CGO_ENABLED=1
    goarch:
      - amd64
    goos:
      - linux
    ldflags:
      - -s -w -X github.com/tubby1981/mokey/server.Version={{.Version}}
      - -extldflags=-static
    tags:
      - sqlite_omit_load_extension
      - osusergo

nfpms:
  - id: mokey
    formats:
      - deb
      - rpm
    maintainer: Andrew E. Bruno <aebruno2@buffalo.edu>
    vendor: University at Buffalo
    homepage: https://github.com/tubby1981/mokey
    license: MIT
    description: |
      FreeIPA self-service account management tool
    overrides:
      deb:
        file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
        scripts:
          postinstall: ./scripts/nfpm/postinstall.sh
      rpm:
        file_name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Arch }}"
        scripts:
          postinstall: ./scripts/nfpm/postinstall.sh
    #rpm:
    #  signature:
    #    key_file: key.gpg
    #deb:
    #  signature:
    #    key_file: key.gpg
    contents:
      - src: ./scripts/nfpm/mokey.toml.default
        dst: /etc/mokey/mokey.toml
        type: config|noreplace
      - src: ./scripts/nfpm/mokey.env
        dst: /etc/default/mokey
      - src: ./scripts/nfpm/translations/*
        dst: /etc/mokey/translations/
        file_info:
          owner: mokey
          group: mokey
      - src: ./scripts/nfpm/mokey.service
        dst: /usr/lib/systemd/system/mokey.service

checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-SNAPSHOT-{{.ShortCommit}}"
changelog:
  sort: desc
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Other
      order: 999
  filters:
    exclude:
      - '^docs:'
      - 'typo'          
